services:
  db:
    image: mysql:5.7
    container_name: nerdo-db-container
    env_file:
      - .db.env
    volumes:
      - db-data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot-network

  bot:
    build: .
    container_name: nerdo-bot-container
    env_file:
      - .env
    networks:
      - bot-network
    depends_on:
      - db

networks:
  bot-network:
    driver: bridge

volumes:
  db-data:
