services:
  bot:
    build: .
    container_name: nerdo-bot-container
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - bot-network

  mysql:
    image: mysql:5.7
    container_name: nerdo-database-container
    env_file:
      - db.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  mysql-data:
